version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Run Prettier
          command: |
            yarn prettier:check
      - run:
          name: Build
          command: |
            yarn pre-publish
